server:
  port: 8050

spring:
  profiles:
    active: @profiles.active@
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: landa-mas-gateway
  security:
    oauth2:
      client:
        registration:
          landa:
            client-id: client
            client-secret: 123456
        provider:
          landa:
            authorization-uri: http://127.0.0.1:8050/landa-mas-oauth/oauth/authorize
            token-uri: http://127.0.0.1:8050/landa-mas-oauth/oauth/token
#            user-info-uri: https://your-subdomain.oktapreview.com/oauth2/v1/userinfo
#            user-name-attribute: sub
#            jwk-set-uri: https://your-subdomain.oktapreview.com/oauth2/v1/keys

##timeout config
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0

##route config
zuul:
  host:
    socket-timeout-millis: 30000
    connect-timeout-millis: 30000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
