## cloud
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: https://landa-mas-eureka-test.landaudev.com/eureka/
#  instance:
#    prefer-ip-address: true

eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}
  client:
    service-url:
      defaultZone: ${vcap.services.eureka.credentials.url}