server:
  port: 8050

spring:
  profiles:
    active: @profiles.active@
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: landa-mas-gateway    # 项目名称尽量用小写


##timeout config
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0

##route config
zuul:
  host:
    socket-timeout-millis: 30000
    connect-timeout-millis: 30000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true